cleanup help

diff --git a/common/zshell/plugins/workplace/functions/_tsw_go b/common/zshell/plugins/workplace/functions/_tsw_go
--- a/common/zshell/plugins/workplace/functions/_tsw_go
+++ b/common/zshell/plugins/workplace/functions/_tsw_go
@@ -1,28 +1,31 @@
 #! /bin/zsh
 #
+
+CMD="${funcstack[2]:-"${FUNCNAME[2]}"}"
+OPT="$(echo ${funcstack[1]:-"${FUNCNAME[1]}"} | sed 's/.*_\([^_]*\)/\1/'"
+
 if (( $@[(I)--help] )) || (( $@[(I)-h] ))
 then
     sed 's/^#/ /'  <<USAGE >&2
 
-# usage: "${funcstack[2]:-"${FUNCNAME[2]}"}" "${funcstack[1]:-"${FUNCNAME[1]}"}"
+# usage: "$CMD" "$OPT"
 #
 #        Find a host(s) to ssh into.
 #
 # Example searches include:
 #
-#   tsw go --mine               # find hosts that have
-#                               # aws/Owner=$USER.zscaler.com attrs.
-#   tsw go --search ...         # use tsh ls search on attributes...
-#   tsw go ip_private=1.1.1.1   # search by a specific attribute.  but then
-#   tsw go --search 1.1.1.1     # also would work...
-#
-#   you can drop the --search, it is a tsh-ism....
+#   $CMD $OPT --mine             # find devboxes owned by $USER
+#   $CMD $OPT --search ...       # use tsh ls search on attributes...
+#   $CMD $OPT ip_private=1.1.1.1 # search by a specific attribute.  but then
+#   $CMD $OPT --search 1.1.1.1   # also would work...
+#   $CMD $OPT 1.1.1.1            # for a single attr search, this also works.
 #
 #   If no hosts match, an error message is printed.
 #   if more than one host matches, we use fzf to allow the user to pick
 #   from the matched criteria.
 #
-#   tsw go                      # short form to search among all available hosts.
+#   $CMD $OPT                    # is short form to search/pick
+#                                # among all available hosts.
 #
 USAGE
     return
@@ -32,10 +35,10 @@ emulate -L zsh -o pipe_fail -o err_return
 
 case $(tsh ls --format=json "$@"  2>&- | jq length) in
 '')
-    echo "tsw go: unknown error" $(tsw ls --format=json "$@" 2>&1)
+    echo "$CMD $OPT: unknown error" $(tsh ls --format=json "$@" 2>&1)
     ;;
 0)
-    echo "tsw go: " "No host matched for criteria:" "$@" >&2
+    echo "$CMD $OPT: No host matched for criteria:" "$@" >&2
     ;;
 1)
     tsh ssh $(tsh ls --format=json "$@" | jq -r '.[].spec.hostname')
diff --git a/common/zshell/plugins/workplace/functions/_tsw_labels b/common/zshell/plugins/workplace/functions/_tsw_labels
--- a/common/zshell/plugins/workplace/functions/_tsw_labels
+++ b/common/zshell/plugins/workplace/functions/_tsw_labels
@@ -1,29 +1,28 @@
 #! /bin/zsh
 #
+
+CMD="${funcstack[2]:-"${FUNCNAME[2]}"}"
+OPT="$(echo ${funcstack[1]:-"${FUNCNAME[1]}"} | sed 's/.*_\([^_]*\)/\1/'"
+
 if (( $@[(I)--help] )) || (( $@[(I)-h] ))
 then
     sed 's/^#/ /'  <<USAGE >&2
 
-# usage: "${funcstack[2]:-"${FUNCNAME[2]}"}" "${funcstack[1]:-"${FUNCNAME[1]}"}"
+# usage: "$CMD" "$OPT"
 #
 #        find all possible labels that can be used to search a machine.
 #
 # Example searches include:
 #
-#   tsw labels --mine               # find hosts that have
-#                               # aws/Owner=$USER.zscaler.com attrs.
-#   tsw labels --search ...         # use tsh ls search on attributes...
-#   tsw labels ip_private=1.1.1.1   # search by a specific attribute.  but then
-#   tsw labels --search 1.1.1.1     # also would work...
-#
-#   you can drop the --search, it is a tsh-ism....
+#   $CMD $OPT --mine               # find devboxes owned by $USER
+#   $CMD $OPT --search ...         # use tsh ls search on attributes...
+#   $CMD $OPT ip_private=1.1.1.1   # search by a specific attribute.  but then
+#   $CMD $OPT --search 1.1.1.1     # also would work...
+#   $CMD $OPT 1.1.1.1              # for a single attr search, this also works..
 #
 #   If no hosts match, an error message is printed.
-#   if more than one host matches, we use fzf to allow the user to pick
-#   from the matched criteria.
 #
-#   tsw labels                      # short form to search among all available hosts.
-#
+#   $CMD $OPT                      # returns all possible labels on all hosts.
 #
 USAGE
     return
@@ -31,10 +30,20 @@ fi
 
 emulate -L zsh -o pipe_fail -o err_return
 
-tsh ls --format=json "$@"                 | \
-jq -C '.[]
-       | .metadata.labels + .spec.cmd_labels
-       | keys
-       | .[]'                             | \
-sort                                      | \
-uniq
+case $(tsh ls --format=json "$@" 2>&- | jq length) in
+'')
+    echo "$CMD $OPT: unknown error" $(tsh ls --format=json "$@" 2>&1)
+    ;;
+0)
+    echo "$CMD $OPT: No host matched for criteria:" "$@" >&2
+    ;;
+*)
+    tsh ls --format=json "$@"                 | \
+    jq -C '.[]
+           | .metadata.labels + .spec.cmd_labels
+           | keys
+           | .[]'                             | \
+    sort                                      | \
+    uniq
+    ;;
+esac
diff --git a/common/zshell/plugins/workplace/functions/_tsw_ls b/common/zshell/plugins/workplace/functions/_tsw_ls
--- a/common/zshell/plugins/workplace/functions/_tsw_ls
+++ b/common/zshell/plugins/workplace/functions/_tsw_ls
@@ -1,30 +1,29 @@
 #! /bin/zsh
 #
+
+CMD="${funcstack[2]:-"${FUNCNAME[2]}"}"
+OPT="$(echo ${funcstack[1]:-"${FUNCNAME[1]}"} | sed 's/.*_\([^_]*\)/\1/'"
+
 if (( $@[(I)--help] )) || (( $@[(I)-h] ))
 then
     sed 's/^#/ /'  <<USAGE >&2
 
-# usage: "${funcstack[2]:-"${FUNCNAME[2]}"}" "${funcstack[1]:-"${FUNCNAME[1]}"}"
+# usage: "$CMD" "$OPT"
 #
 #        List machines that match the arg spec. 
 #
 # Example searches include:
 #
-#   tsw ls --mine               # find hosts that have
-#                               # aws/Owner=$USER.zscaler.com attrs.
-#   tsw ls --search ...         # use tsh ls search on attributes...
-#   tsw ls ip_private=1.1.1.1   # search by a specific attribute.  but then
-#   tsw ls --search 1.1.1.1     # also would work...
-#
-#   you can drop the --search, it is a tsh-ism....
+#   $CMD $OPT --mine             # find devboxes owned by $USER
+#   $CMD $OPT --search ...       # use tsh ls to search on attributes...
+#   $CMD $OPT ip_private=1.1.1.1 # search by a specific attribute.  but then
+#   $CMD $OPT --search 1.1.1.1   # also would work...
+#   $CMD $OPT 1.1.1.1            # for a single attr search, this also works...
 #
 #   If no hosts match, an error message is printed.
-#   if more than one host matches, we use fzf to allow the user to pick
-#   from the matched criteria.
 #
-#   tsw ls                      # short form to search among all available hosts.
-#
-# Outputs a csv format that can be run through csvlook, in the csvkit package.
+# Outputs a csv format list that can be run through csvlook,
+# in the csvkit package.
 #
 USAGE
     return
@@ -32,15 +31,25 @@ fi
 
 emulate -L zsh -o pipe_fail -o err_return
 
-print "hostname,Private IP,instance-id,HW Type,expiry";
-tsh ls --format=json "$@"                | \
-    jq -r '.[]
-           | [ .spec.hostname,
-               ( .spec.cmd_labels |
-                   .ip_private.result,
-                   .aws_instance_id.result,
-                   .hwtype.result[:7]
-               ),
-               .metadata.expires[:10]
-             ]
-           | @csv'
+case $(tsh ls --format=json "$@" 2>&- | jq length) in
+'')
+    echo "$CMD $OPT: unknown error" $(tsh ls --format=json "$@" 2>&1)
+    ;;
+0)
+    echo "$CMD $OPT: No host matched for criteria:" "$@" >&2
+    ;;
+*)
+    print "hostname,Private IP,instance-id,HW Type,expiry";
+    tsh ls --format=json "$@"                | \
+        jq -r '.[]
+               | [ .spec.hostname,
+                   ( .spec.cmd_labels |
+                       .ip_private.result,
+                       .aws_instance_id.result,
+                       .hwtype.result[:7]
+                   ),
+                   .metadata.expires[:10]
+                 ]
+               | @csv'
+    ;;
+esac
diff --git a/common/zshell/plugins/workplace/functions/_tsw_my-labels b/common/zshell/plugins/workplace/functions/_tsw_my-labels
--- a/common/zshell/plugins/workplace/functions/_tsw_my-labels
+++ b/common/zshell/plugins/workplace/functions/_tsw_my-labels
@@ -1,28 +1,28 @@
 #! /usr/bin/env bash
 #
+
+CMD="${funcstack[2]:-"${FUNCNAME[2]}"}"
+OPT="$(echo ${funcstack[1]:-"${FUNCNAME[1]}"} | sed 's/.*_\([^_]*\)/\1/'"
+
 if (( $@[(I)--help] )) || (( $@[(I)-h] ))
 then
     sed 's/^#/ /'  <<USAGE >&2
 
-# usage: "${funcstack[2]:-"${FUNCNAME[2]}"}" "${funcstack[1]:-"${FUNCNAME[1]}"}"
+# usage: "$CMD" "$OPT"
 #
 # list the labels affixed to machines that I am designated as owner.
 #
 # Example searches include:
 #
-#   tsw my-labels --mine               # find hosts that have
-#                               # aws/Owner=$USER.zscaler.com attrs.
-#   tsw my-labels --search ...         # use tsh ls search on attributes...
-#   tsw my-labels ip_private=1.1.1.1   # search by a specific attribute.  but then
-#   tsw my-labels --search 1.1.1.1     # also would work...
+#   $CMD $OPT --mine               # find devboxes owned by $USER
+#   $CMD $OPT --search ...         # use tsh ls search on attributes...
+#   $CMD $OPT ip_private=1.1.1.1   # search by a specific attribute.  but then
+#   $CMD $OPT --search 1.1.1.1     # also would work...
+#   $CMD $OPT 1.1.1.1              # for a single attr search, this also works..
 #
-#   you can drop the --search, it is a tsh-ism....
+#   If no hosts match, an error message is printed
 #
-#   If no hosts match, an error message is printed.
-#   if more than one host matches, we use fzf to allow the user to pick
-#   from the matched criteria.
-#
-#   tsw my-labels                      # short form to search among all available hosts.
+#   $CMD $OPT              # prints labels on all devboxes owned by $USER
 #
 #
 USAGE
@@ -37,13 +37,22 @@ if [[ $# == 0 ]] ; then
     set -- "aws/Owner=$USER@zscaler.com"
 fi
 
-tsh ls --format=json "$@"                  | \
-jq --raw-output '.[] 
-                 | .metadata.labels
-                 + (
-                   .spec.cmd_labels
-                   | .[]
-                   |= .result
-                 )'
-
+case $(tsh ls --format=json "$@" 2>&- | jq length) in
+'')
+    echo "$CMD $OPT: unknown error" $(tsh ls --format=json "$@" 2>&1)
+    ;;
+0)
+    echo "$CMD $OPT: No host matched for criteria:" "$@" >&2
+    ;;
+*)
+    tsh ls --format=json "$@"                  | \
+    jq --raw-output '.[] 
+                    | .metadata.labels
+                    + (
+                    .spec.cmd_labels
+                    | .[]
+                    |= .result
+                    )'
+    ;;
+esac
 
